### ISSUE TITLE
Improve handling of chat messages

### ISSUE THREAD

**Issue by awillinger** [klyve/KZTimerGlobal#70]
This is more of an request than a bug report.

Currently, chat tags are rewritten in a direct "say" and "say_team" command hook in hooks.sp (https://github.com/klyve/KZTimerGlobal/blob/master/scripting/kztimerGlobal/hooks.sp#L308).
While this is working fine for the KZ plugin, it causes two problems:
a.) the entirety of chat logging is blocked. This prevents external services (such as gameMe) from storing chat logs, and even the gameserver itself from writing them into its own log files.
b.) other plugin can't modify the chat messages anymore. If I have, for example, a custom VIP and Store system, they will never see the chat messages and therefore can't modify them either.

My suggestion would be to add another CVar (sth. like kz_chat_mode), which supports 3 values:
1 - behaviour as it is currently (hook say/say_team)
2 - use https://forums.alliedmods.net/showthread.php?t=286913 to rewrite chat messages
3 - do not touch the chat at all

With the latter option, a native would have to be added (like KZ_GetChatTag / KZ_GetChatColor), so other plugins can call it and handle the chat messages.

Would it be possible to refactor the plugin in that way? I don't really want to do the modifications myself, as they would get overwritten with the next update (and I don't have time to re-implement them every time).
Thanks in advance!

**Comment by sneak-it** [comment]
I agree, this would be a huge improvement. Cksurf (which is based off of kztimer initially) has an option to do this (ck_chat_enable) in which the plugin's chat processing can be completely disabled. There is no way to remotely monitor chat, log it, or properly filter it in KZTimer's current state.
